const BASE_OPENSEA_URL = "https://api.opensea.io/asset";
const COLLECTION_CONTRACT = "0x9251dec8df720c2adf3b6f46d968107cbbadf4d4";
const COLLECTION_URL = `${BASE_OPENSEA_URL}/${COLLECTION_CONTRACT}`;
const COLLECTION_TOKEN_COUNT = 7331;

export { COLLECTION_URL, COLLECTION_TOKEN_COUNT };
